### ISSUE TITLE
Event List Page

### ISSUE THREAD

**Issue by azhamdev** [azhamdev/devcrewproject#8]
## TODO
- [ ] Make Event List UI
- [ ] Event List Page Functionality
- [ ] Make page as [find] so the Link should be /find
___
### Notes : 

Please create beautiful Register UI first in like the figma, then think about Functionality, Decouple the UI and Logics.

[Link](https://www.figma.com/file/SAQwpje0boezehhCFA4QRZ/eventboom?type=design&node-id=0%3A1&mode=design&t=KconuE5yNfYguIyD-1)
